### ISSUE TITLE
Resizing Messages

### ISSUE THREAD

**Issue by d4tocchini** [the-grid/ced#2]
iFrame should resize to CM contents by default (perhaps a collapsed/scrollable state should be available but isn't as important).  

Needed:
- Messages for setting size of iFrame onload & when height changes

**Comment by forresto** [comment]
:+1: I'm ready to get this working on the /ed side.

**Comment by forresto** [comment]
After hacking it in as a message from ced (#5) I noticed that could measure from ed (`iframe.contentDocument.body.clientHeight`) ... this might make for less code across repos, to look at that on change.

**Comment by forresto** [comment]
Re: Jan 19 :point_up_2: ... `clientHeight` didn't work as widget never gets smaller.
